<center> <img src = https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/hh%20label.jpg alt="drawing" style="width:400px;">

# <center> Проект: Анализ резюме из HeadHunter

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Исследование структуры данных

1. Прочитайте данные с помощью библиотеки Pandas. Совет: перед чтением обратите внимание на разделитель внутри файла.

In [11]:
#ваш код здесь
file_path = r"C:\Датасет для сессионного задания Пайтон\dst-3.0_16_1_hh_database.csv" 
HeadHunter_data = pd.read_csv(file_path, sep=';')

2. Выведите несколько первых (последних) строк таблицы, чтобы убедиться в том, что ваши данные не повреждены. Ознакомьтесь с признаками и их структурой.

In [12]:
#ваш код здесь

display(HeadHunter_data.head())
display(HeadHunter_data.tail())

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
0,"Мужчина , 39 лет , родился 27 ноября 1979",29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,Неоконченное высшее образование 2000 Балтийск...,16.04.2019 15:59,Имеется собственный автомобиль
1,"Мужчина , 60 лет , родился 20 марта 1959",40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",Высшее образование 1981 Военно-космическая ак...,12.04.2019 08:42,Не указано
2,"Женщина , 36 лет , родилась 12 августа 1982",20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,Среднее специальное образование 2002 Профессио...,16.04.2019 08:35,Не указано
3,"Мужчина , 38 лет , родился 25 июня 1980",100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,Высшее образование 2002 Саратовский государст...,08.04.2019 14:23,Не указано
4,"Женщина , 26 лет , родилась 3 марта 1993",140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,Высшее образование 2015 Кгу Психологии и педаг...,22.04.2019 10:32,Не указано

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
44739,"Мужчина , 30 лет , родился 17 января 1989",50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","Опыт работы 7 лет 7 месяцев Финансист, аналит...","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,Высшее образование 2015 Московский гуманитарн...,22.04.2019 12:32,Не указано
44740,"Мужчина , 27 лет , родился 5 марта 1992",39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...","Опыт работы 7 лет Системный администратор, IT...",ИП Пестрецов,Предприниматель,Высшее образование (Бакалавр) 2016 Воронежски...,22.04.2019 13:11,Не указано
44741,"Женщина , 48 лет , родилась 26 декабря 1970",40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,Высшее образование 2000 Южно-Уральский госуда...,09.04.2019 05:07,Не указано
44742,"Мужчина , 24 года , родился 6 октября 1994",20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,IQ-Maxima,Менеджер проектов,Высшее образование 2015 Тамбовский государств...,26.04.2019 14:25,Имеется собственный автомобиль
44743,"Мужчина , 38 лет , родился 25 апреля 1980",120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,Высшее образование 1997 Южно-Российский госуд...,05.07.2018 20:15,Не указано

3. Выведите основную информацию о числе непустых значений в столбцах и их типах в таблице.

In [13]:
#ваш код здесь
HeadHunter_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Пол, возраст                     44744 non-null  object
 1   ЗП                               44744 non-null  object
 2   Ищет работу на должность:        44744 non-null  object
 3   Город, переезд, командировки     44744 non-null  object
 4   Занятость                        44744 non-null  object
 5   График                           44744 non-null  object
 6   Опыт работы                      44576 non-null  object
 7   Последнее/нынешнее место работы  44743 non-null  object
 8   Последняя/нынешняя должность     44742 non-null  object
 9   Образование и ВУЗ                44744 non-null  object
 10  Обновление резюме                44744 non-null  object
 11  Авто                             44744 non-null  object
dtypes: object(12)
memory usage: 4.1+ MB

4. Обратите внимание на информацию о числе непустых значений.

In [14]:
#ваш код здесь
HeadHunter_data[['Опыт работы','Последнее/нынешнее место работы', 'Последняя/нынешняя должность']].count()
# В данных столбцах присутствуют пустые значения, так как количество непустых значений в столбце меньше, чем количество строк в таблице (44744)
 #6   Опыт работы                      44576 non-null  object
 #7   Последнее/нынешнее место работы  44743 non-null  object
 #8   Последняя/нынешняя должность     44742 non-null  object

Опыт работы                        44576
Последнее/нынешнее место работы    44743
Последняя/нынешняя должность       44742
dtype: int64

5. Выведите основную статистическую информацию о столбцах.

In [15]:
#ваш код здесь
HeadHunter_data.describe()

,"Пол, возраст",ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Образование и ВУЗ,Обновление резюме,Авто
count,44744,44744,44744,44744,44744,44744,44576,44743,44742,44744,44744,44744
unique,16003,690,14929,10063,38,47,44413,30214,16927,40148,18838,2
top,"Мужчина , 32 года , родился 17 сентября 1986",50000 руб.,Системный администратор,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 10 лет 8 месяцев Апрель 2018 — по...,Индивидуальное предпринимательство / частная п...,Системный администратор,Высшее образование 2014 Тюменский Государствен...,07.05.2019 09:50,Не указано
freq,18,4064,3099,1261,30026,22727,3,935,2062,4,25,32268

# Преобразование данных

1. Начнем с простого - с признака **"Образование и ВУЗ"**. Его текущий формат это: **<Уровень образования год выпуска ВУЗ специальность...>**. Например:
* Высшее образование 2016 Московский авиационный институт (национальный исследовательский университет)...
* Неоконченное высшее образование 2000  Балтийская государственная академия рыбопромыслового флота…
Нас будет интересовать только уровень образования.

Создайте с помощью функции-преобразования новый признак **"Образование"**, который должен иметь 4 категории: "высшее", "неоконченное высшее", "среднее специальное" и "среднее".

Выполните преобразование, ответьте на контрольные вопросы и удалите признак "Образование и ВУЗ".

Совет: обратите внимание на структуру текста в столбце **"Образование и ВУЗ"**. Гарантируется, что текущий уровень образования соискателя всегда находится в первых 2ух слов и начинается с заглавной буквы. Воспользуйтесь этим.

*Совет: проверяйте полученные категории, например, с помощью метода unique()*

In [16]:
#ваш код здесь
# СОздадим копию датасета для преобразования
HeadHunter_data_feat_eng = HeadHunter_data.copy()

educ_train = HeadHunter_data_feat_eng['Образование и ВУЗ']

cat_education = ["высшее", "неоконченное высшее", "среднее специальное","среднее"]

def transform_education(education):
    
    education = education.split()[:2]
    if education[0] == 'Высшее':
        return "высшее"
    elif education[1] == 'специальное':
        return "среднее специальное"
    elif education[0] == 'Среднее':
        return "среднее"
    elif education[0] == 'Неоконченное':
        return "неоконченное высшее"
    return education

educ_train = educ_train.apply(transform_education)
HeadHunter_data_feat_eng['Образование'] = educ_train
HeadHunter_data_feat_eng['Образование'] = HeadHunter_data_feat_eng['Образование'].astype('category')

HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop('Образование и ВУЗ', axis=1)
HeadHunter_data_feat_eng['Образование'].unique()

['неоконченное высшее', 'высшее', 'среднее специальное', 'среднее']
Categories (4, object): ['высшее', 'неоконченное высшее', 'среднее', 'среднее специальное']

2. Теперь нас интересует столбец **"Пол, возраст"**. Сейчас он представлен в формате **<Пол , возраст , дата рождения >**. Например:
* Мужчина , 39 лет , родился 27 ноября 1979 
* Женщина , 21 год , родилась 13 января 2000
Как вы понимаете, нам необходимо выделить каждый параметр в отдельный столбец.

Создайте два новых признака **"Пол"** и **"Возраст"**. При этом важно учесть:
* Признак пола должен иметь 2 уникальных строковых значения: 'М' - мужчина, 'Ж' - женщина. 
* Признак возраста должен быть представлен целыми числами.

Выполните преобразование, ответьте на контрольные вопросы и удалите признак **"Пол, возраст"** из таблицы.

*Совет: обратите внимание на структуру текста в столбце, в части на то, как разделены параметры пола, возраста и даты рождения между собой - символом ' , '. 
Гарантируется, что структура одинакова для всех строк в таблице. Вы можете воспользоваться этим.*

In [17]:
#ваш код здесь

gender_age_train = HeadHunter_data_feat_eng['Пол, возраст']


def transform_gender(gender_age):
    gender = gender_age.split(',')[0]
    gender = gender.strip()
    if gender == 'Мужчина':
        gender = 'М'
    else:
        gender = 'Ж'
    return gender

def transform_age(gender_age):
    age = gender_age.split(',')[1]
    age = age.strip()
    age = age.split(' ')[0]
    return int(age)

gender_train = gender_age_train.apply(transform_gender)

age_train = gender_age_train.apply(transform_age)

HeadHunter_data_feat_eng['Пол'] = gender_train
HeadHunter_data_feat_eng['Пол'] = HeadHunter_data_feat_eng['Пол'].astype('category')

HeadHunter_data_feat_eng['Возраст'] = age_train

HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop('Пол, возраст', axis=1)

HeadHunter_data_feat_eng

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Опыт работы,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...",Опыт работы 16 лет 10 месяцев Август 2010 — п...,"МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,М,39
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Опыт работы 19 лет 5 месяцев Январь 2000 — по...,Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 08:42,Не указано,высшее,М,60
2,20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,Опыт работы 10 лет 3 месяца Октябрь 2004 — Де...,ПАО Сбербанк,Кассир-операционист,16.04.2019 08:35,Не указано,среднее специальное,Ж,36
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",Опыт работы 18 лет 9 месяцев Август 2017 — Ап...,OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,М,38
4,140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Опыт работы 5 лет 7 месяцев Региональный мене...,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Ж,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44739,50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","Опыт работы 7 лет 7 месяцев Финансист, аналит...","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,22.04.2019 12:32,Не указано,высшее,М,30
44740,39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...","Опыт работы 7 лет Системный администратор, IT...",ИП Пестрецов,Предприниматель,22.04.2019 13:11,Не указано,высшее,М,27
44741,40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа",Опыт работы 21 год 5 месяцев Январь 1998 — по...,"ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,09.04.2019 05:07,Не указано,высшее,Ж,48
44742,20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,Опыт работы 3 года 10 месяцев Контент-менедже...,IQ-Maxima,Менеджер проектов,26.04.2019 14:25,Имеется собственный автомобиль,высшее,М,24
44743,120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,Опыт работы 15 лет 10 месяцев Руководитель пр...,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,05.07.2018 20:15,Не указано,высшее,М,38

3. Следующим этапом преобразуем признак **"Опыт работы"**. Его текущий формат - это: **<Опыт работы: n лет m месяцев, периоды работы в различных компаниях…>**. 

Из столбца нам необходимо выделить общий опыт работы соискателя в месяцах, новый признак назовем "Опыт работы (месяц)"

Для начала обсудим условия решения задачи:
* Во-первых, в данном признаке есть пропуски. Условимся, что если мы встречаем пропуск, оставляем его как есть (функция-преобразование возвращает NaN)
* Во-вторых, в данном признаке есть скрытые пропуски. Для некоторых соискателей в столбце стоит значения "Не указано". Их тоже обозначим как NaN (функция-преобразование возвращает NaN)
* В-третьих, нас не интересует информация, которая описывается после указания опыта работы (периоды работы в различных компаниях)
* В-четвертых, у нас есть проблема: опыт работы может быть представлен только в годах или только месяцах. Например, можно встретить следующие варианты:
    * Опыт работы 3 года 2 месяца…
    * Опыт работы 4 года…
    * Опыт работы 11 месяцев…
    * Учитывайте эту особенность в вашем коде

Учитывайте эту особенность в вашем коде

В результате преобразования у вас должен получиться столбец, содержащий информацию о том, сколько месяцев проработал соискатель.
Выполните преобразование, ответьте на контрольные вопросы и удалите столбец **"Опыт работы"** из таблицы.

In [18]:
#ваш код здесь

expirience_train = HeadHunter_data['Опыт работы']

import re

pattern = re.compile(
    r"опыт работы\s+"
    r"(?:(?P<years>\d+)\s*(?:год|года|лет))?"
    r"\s*"
    r"(?:(?P<months>\d+)\s*(?:месяц|месяца|месяцев|мес))?",
    flags=re.IGNORECASE,
)


def transform_expirience(text: str):
    if text is np.nan or pd.isna(text):
        return np.nan
    if text == "Не указано":
        return np.nan

    match = pattern.search(text)

    if not match:
        return np.nan

    years = match.group("years")
    months = match.group("months")

    years = int(years) if years else 0
    months = int(months) if months else 0

    return years * 12 + months


expirience_train_month = expirience_train.apply(transform_expirience)

HeadHunter_data_feat_eng['Опыт работы (месяц)'] = expirience_train_month

HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop('Опыт работы', axis=1)

HeadHunter_data_feat_eng

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Опыт работы (месяц)
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,М,39,202.0
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 08:42,Не указано,высшее,М,60,233.0
2,20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,16.04.2019 08:35,Не указано,среднее специальное,Ж,36,123.0
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,М,38,225.0
4,140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Ж,26,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
44739,50000 руб.,"Финансист, аналитик, экономист, бухгалтер, мен...","Тверь , готов к переезду (Москва, Химки) , гот...",полная занятость,"полный день, удаленная работа","ООО ""IAS"" (независимый участник объединения Ru...",Руководитель субгруппы,22.04.2019 12:32,Не указано,высшее,М,30,91.0
44740,39000 руб.,"Системный администратор, IT-специалист","Липецк , готов к переезду , готов к командировкам","проектная работа, частичная занятость, полная ...","удаленная работа, гибкий график, полный день, ...",ИП Пестрецов,Предприниматель,22.04.2019 13:11,Не указано,высшее,М,27,84.0
44741,40000 руб.,"Аналитик данных, Математик","Челябинск , готова к переезду , готова к редки...",полная занятость,"полный день, удаленная работа","ОАО «ЧМК», Исследовательско-Технологический Це...",Начальник группы аналитики,09.04.2019 05:07,Не указано,высшее,Ж,48,257.0
44742,20000 руб.,Контент-менеджер,"Тамбов , не готов к переезду , не готов к кома...","частичная занятость, полная занятость",удаленная работа,IQ-Maxima,Менеджер проектов,26.04.2019 14:25,Имеется собственный автомобиль,высшее,М,24,36.0
44743,120000 руб.,Руководитель проекта,"Москва , не готов к переезду , не готов к кома...",полная занятость,полный день,ПАО ГК ТНС энерго,Руководитель отдела технической поддержки,05.07.2018 20:15,Не указано,высшее,М,38,190.0

4. Хорошо идем! Следующий на очереди признак "Город, переезд, командировки". Информация в нем представлена в следующем виде: **<Город , (метро) , готовность к переезду (города для переезда) , готовность к командировкам>**. В скобках указаны необязательные параметры строки. Например, можно встретить следующие варианты:

* Москва , не готов к переезду , готов к командировкам
* Москва , м. Беломорская , не готов к переезду, не готов к командировкам
* Воронеж , готов к переезду (Сочи, Москва, Санкт-Петербург) , готов к командировкам

Создадим отдельные признаки **"Город"**, **"Готовность к переезду"**, **"Готовность к командировкам"**. При этом важно учесть:

* Признак **"Город"** должен содержать только 4 категории: "Москва", "Санкт-Петербург" и "город-миллионник" (их список ниже), остальные обозначьте как "другие".

    Список городов-миллионников:
    
   <code>million_cities = ['Новосибирск', 'Екатеринбург','Нижний Новгород','Казань', 'Челябинск','Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж','Волгоград']
    </code>
    Инфорация о метро, рядом с которым проживает соискатель нас не интересует.
* Признак **"Готовность к переезду"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к переезду в признаке "Город, переезд, командировки". Например:
    * … , готов к переезду , …
    * … , не готова к переезду , …
    * … , готова к переезду (Москва, Санкт-Петербург, Ростов-на-Дону)
    * … , хочу переехать (США) , …
    
    Нас интересует только сам факт возможности или желания переезда.
* Признак **"Готовность к командировкам"** должен иметь два возможных варианта: True или False. Обратите внимание, что возможны несколько вариантов описания готовности к командировкам в признаке "Город, переезд, командировки". Например:
    * … , готов к командировкам , … 
    * … , готова к редким командировкам , …
    * … , не готов к командировкам , …
    
    Нас интересует только сам факт готовности к командировке.
    
    Еще один важный факт: при выгрузки данных у некоторых соискателей "потерялась" информация о готовности к командировкам. Давайте по умолчанию будем считать, что такие соискатели не готовы к командировкам.
    
Выполните преобразования и удалите столбец **"Город, переезд, командировки"** из таблицы.

*Совет: обратите внимание на то, что структура текста может меняться в зависимости от указания ближайшего метро. Учите это, если будете использовать порядок слов в своей программе.*

In [19]:
#ваш код здесь
city_relocation_train = HeadHunter_data_feat_eng['Город, переезд, командировки']

# Создаем столбец город
def transform_city(city_relocation):
    if pd.isna(city_relocation):
        return np.nan
    
    million_cities = ['Новосибирск', 'Екатеринбург', 'Нижний Новгород', 'Казань', 'Челябинск', 'Омск', 'Самара', 'Ростов-на-Дону', 'Уфа', 'Красноярск', 'Пермь', 'Воронеж', 'Волгоград' ]
    city_words = city_relocation.split()
    
    city = city_words[0]
    if city in million_cities:
        city = 'город-миллионник'
    elif city not in million_cities and city != 'Москва' and city != 'Санкт-Петербург':
        city = 'другие'
        
    return city

city = city_relocation_train.apply(transform_city)

HeadHunter_data_feat_eng['Город'] = city
HeadHunter_data_feat_eng['Город'].value_counts(normalize=True)

# Создаем столбец Готовность к переезду
pattern = 'не готов к переезду|не готова к переезду'

relocation = ~city_relocation_train.str.contains(pattern, case=False, na=False)

relocation.value_counts()

HeadHunter_data_feat_eng['Готовность к переезду'] = relocation
HeadHunter_data_feat_eng['Готовность к переезду'].value_counts(normalize=True)

# Создаем столбец Готовность к командировкам
pattern1 = 'не готов к командировкам|не готова к командировкам'

work_trip = ~city_relocation_train.str.contains(pattern1, case=False, na=False)



HeadHunter_data_feat_eng['Готовность к командировкам'] = work_trip
HeadHunter_data_feat_eng['Готовность к командировкам'].value_counts(normalize=True)


HeadHunter_data_feat_eng.head()

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Занятость,График,Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,Опыт работы (месяц),Город,Готовность к переезду,Готовность к командировкам
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, ва...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,М,39,202.0,другие,False,False
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, полный день, сменный график, уд...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 08:42,Не указано,высшее,М,60,233.0,другие,False,True
2,20000 руб.,Оператор,"Тверь , не готова к переезду , не готова к ком...",полная занятость,полный день,ПАО Сбербанк,Кассир-операционист,16.04.2019 08:35,Не указано,среднее специальное,Ж,36,123.0,другие,False,False
3,100000 руб.,Веб-разработчик (HTML / CSS / JS / PHP / базы ...,"Саратов , не готов к переезду , готов к редким...","частичная занятость, проектная работа, полная ...","гибкий график, удаленная работа",OpenSoft,Инженер-программист,08.04.2019 14:23,Не указано,высшее,М,38,225.0,другие,False,True
4,140000 руб.,Региональный менеджер по продажам,"Москва , не готова к переезду , готова к коман...",полная занятость,полный день,Мармелад,Менеджер по продажам,22.04.2019 10:32,Не указано,высшее,Ж,26,67.0,Москва,False,True

5. Рассмотрим поближе признаки **"Занятость"** и **"График"**. Сейчас признаки представляют собой набор категорий желаемой занятости (полная занятость, частичная занятость, проектная работа, волонтерство, стажировка) и желаемого графика работы (полный день, сменный график, гибкий график, удаленная работа, вахтовый метод).
На сайте hh.ru соискатель может указывать различные комбинации данных категорий, например:
* полная занятость, частичная занятость
* частичная занятость, проектная работа, волонтерство
* полный день, удаленная работа
* вахтовый метод, гибкий график, удаленная работа, полная занятость

Такой вариант признаков имеет множество различных комбинаций, а значит множество уникальных значений, что мешает анализу. Нужно это исправить!

Давайте создадим признаки-мигалки для каждой категории: если категория присутствует в списке желаемых соискателем, то в столбце на месте строки рассматриваемого соискателя ставится True, иначе - False.

Такой метод преобразования категориальных признаков называется One Hot Encoding и его схема представлена на рисунке ниже:
<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/ohe.jpg>
Выполните данное преобразование для признаков "Занятость" и "График", ответьте на контрольные вопросы, после чего удалите их из таблицы

In [20]:
#ваш код здесь
# Создаем признаки занятости
employment_words = ['полная занятость', 'частичная занятость', 'проектная работа', 'волонтерство', 'стажировка']

for employment_type in employment_words:
    HeadHunter_data_feat_eng[employment_type] = HeadHunter_data_feat_eng['Занятость'].str.contains(
        employment_type, case=False, na=False
    )

# Создаем признаки графика
work_schedule_words = ['полный день', 'сменный график', 'гибкий график', 'удалённая работа', 'вахтовый метод']

for schedule_type in work_schedule_words:
    HeadHunter_data_feat_eng[schedule_type] = HeadHunter_data_feat_eng['График'].str.contains(
        schedule_type, case=False, na=False
    )

In [21]:
HeadHunter_data_feat_eng.head()
HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop(['Занятость', 'График'], axis=1)
HeadHunter_data_feat_eng.head(2)

,ЗП,Ищет работу на должность:,"Город, переезд, командировки",Последнее/нынешнее место работы,Последняя/нынешняя должность,Обновление резюме,Авто,Образование,Пол,Возраст,...,полная занятость,частичная занятость,проектная работа,волонтерство,стажировка,полный день,сменный график,гибкий график,удалённая работа,вахтовый метод
0,29000 руб.,Системный администратор,"Советск (Калининградская область) , не готов к...","МАОУ ""СОШ № 1 г.Немана""",Системный администратор,16.04.2019 15:59,Имеется собственный автомобиль,неоконченное высшее,М,39,...,True,True,True,False,False,True,True,True,False,True
1,40000 руб.,Технический писатель,"Королев , не готов к переезду , готов к редким...",Временный трудовой коллектив,"Менеджер проекта, Аналитик, Технический писатель",12.04.2019 08:42,Не указано,высшее,М,60,...,True,True,True,False,False,True,True,True,False,False

6. (2 балла) Наконец, мы добрались до самого главного и самого важного - признака заработной платы **"ЗП"**. 
В чем наша беда? В том, что помимо желаемой заработной платы соискатель указывает валюту, в которой он бы хотел ее получать, например:
* 30000 руб.
* 50000 грн.
* 550 USD

Нам бы хотелось видеть заработную плату в единой валюте, например, в рублях. Возникает вопрос, а где взять курс валют по отношению к рублю?

На самом деле язык Python имеет в арсенале огромное количество возможностей получения данной информации, от обращения к API Центробанка, до использования специальных библиотек, например pycbrf. Однако, это не тема нашего проекта.

Поэтому мы пойдем в лоб: обратимся к специальным интернет-ресурсам для получения данных о курсе в виде текстовых файлов. Например, MDF.RU, данный ресурс позволяет удобно экспортировать данные о курсах различных валют и акций за указанные периоды в виде csv файлов. Мы уже сделали выгрузку курсов валют, которые встречаются в наших данных за период с 29.12.2017 по 05.12.2019. Скачать ее вы можете **на платформе**

Создайте новый DataFrame из полученного файла. В полученной таблице нас будут интересовать столбцы:
* "currency" - наименование валюты в ISO кодировке,
* "date" - дата, 
* "proportion" - пропорция, 
* "close" - цена закрытия (последний зафиксированный курс валюты на указанный день).


Перед вами таблица соответствия наименований иностранных валют в наших данных и их общепринятых сокращений, которые представлены в нашем файле с курсами валют. Пропорция - это число, за сколько единиц валюты указан курс в таблице с курсами. Например, для казахстанского тенге курс на 20.08.2019 составляет 17.197 руб. за 100 тенге, тогда итоговый курс равен - 17.197 / 100 = 0.17197 руб за 1 тенге.
Воспользуйтесь этой информацией в ваших преобразованиях.

<img src=https://raw.githubusercontent.com/AndreyRysistov/DatasetsForPandas/main/table.jpg>


Осталось только понять, откуда брать дату, по которой определяется курс? А вот же она - в признаке **"Обновление резюме"**, в нем содержится дата и время, когда соискатель выложил текущий вариант своего резюме. Нас интересует только дата, по ней бы и будем сопоставлять курсы валют.

Теперь у нас есть вся необходимая информация для того, чтобы создать признак "ЗП (руб)" - заработная плата в рублях.

После ответа на контрольные вопросы удалите исходный столбец заработной платы "ЗП" и все промежуточные столбцы, если вы их создавали.

Итак, давайте обсудим возможный алгоритм преобразования: 
1. Перевести признак "Обновление резюме" из таблицы с резюме в формат datetime и достать из него дату. В тот же формат привести признак "date" из таблицы с валютами.
2. Выделить из столбца "ЗП" сумму желаемой заработной платы и наименование валюты, в которой она исчисляется. Наименование валюты перевести в стандарт ISO согласно с таблицей выше.
3. Присоединить к таблице с резюме таблицу с курсами по столбцам с датой и названием валюты (подумайте, какой тип объединения надо выбрать, чтобы в таблице с резюме сохранились данные о заработной плате, изначально представленной в рублях). Значение close для рубля заполнить единицей 1 (курс рубля самого к себе)
4. Умножить сумму желаемой заработной платы на присоединенный курс валюты (close) и разделить на пропорцию (обратите внимание на пропуски после объединения в этих столбцах), результат занести в новый столбец "ЗП (руб)".

In [22]:
#ваш код здесь
# Загружаем таблицу с курсами валют, удаляем лишние столбцы, преобразуем столбец date
exchange_rates = pd.read_csv('C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\ExchangeRates.csv')
exchange_rates = exchange_rates.drop(['per', 'time', 'vol'], axis=1)
exchange_rates['date'] = pd.to_datetime(exchange_rates['date'], dayfirst=True)

# Выделяем дату из столбца Обновление резюме
update_resume_date = pd.to_datetime(HeadHunter_data_feat_eng['Обновление резюме'], dayfirst=True)
update_resume_date = update_resume_date.dt.date
HeadHunter_data_feat_eng['Обновление резюме'] = update_resume_date

# Выделяем значение ЗП и валюту, приводим валюту к ISO
salary_train = HeadHunter_data_feat_eng['ЗП']

currency_name_dict = {'грн.':'UAH', 'USD':'USD', 'EUR':'EUR', 'бел.руб.':'BYN', 'KGS':'KGS', 'сум':'UZS', 'AZN':'AZN', 'KZT':'KZT', 'руб.':'руб'}
   
salary = salary_train.apply(lambda x: x.split()[0])

currency = salary_train.apply(lambda x: x.split()[1])

def transform_currency(currency):
    if currency in currency_name_dict:
        currency_ISO = currency_name_dict[currency]
        return currency_ISO
    
currency_ISO = currency.apply(transform_currency)

HeadHunter_data_feat_eng['salary'] = salary

HeadHunter_data_feat_eng['currency'] = currency_ISO

# Объединяем таблицы с резюме и курсами валют
HeadHunter_data_feat_eng_train = HeadHunter_data_feat_eng.copy()
HeadHunter_data_feat_eng_train['Обновление резюме'] = pd.to_datetime(HeadHunter_data_feat_eng['Обновление резюме'], dayfirst=True)

merge = pd.merge(
    HeadHunter_data_feat_eng_train, 
    exchange_rates, 
    left_on=['Обновление резюме', 'currency'], 
    right_on=['date', 'currency'], 
    how='left' # или 'left', 'right', 'outer'
)

# Заполняем пропуски, получившиеся при объединении
close = merge['close'].fillna(value=1)
merge['close'] = close

proportion = merge['proportion'].fillna(value=1)
merge['proportion'] = proportion

merge['salary'] = merge['salary'].astype(int)

# Рассчитываем сумму ЗП в рублях
salary_rub = (merge['salary']*merge['close'])/merge['proportion']


merge['ЗП (руб)'] = salary_rub

merge = merge.drop(['ЗП', 'salary', 'currency', 'date', 'close', 'proportion'], axis=1)

C:\Users\troyd\AppData\Local\Temp\ipykernel_11252\2526520288.py:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  exchange_rates['date'] = pd.to_datetime(exchange_rates['date'], dayfirst=True)

In [23]:
HeadHunter_data_feat_eng = merge
HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop(['Город, переезд, командировки'], axis=1)

In [24]:
HeadHunter_data_feat_eng['Обновление резюме'] = HeadHunter_data_feat_eng['Обновление резюме'].astype(object)
HeadHunter_data_feat_eng['Образование'] = HeadHunter_data_feat_eng['Образование'].astype(object)
HeadHunter_data_feat_eng['Пол'] = HeadHunter_data_feat_eng['Пол'].astype(object)
HeadHunter_data_feat_eng.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44744 entries, 0 to 44743
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Ищет работу на должность:        44744 non-null  object
 1   Последнее/нынешнее место работы  44743 non-null  object
 2   Последняя/нынешняя должность     44742 non-null  object
 3   Обновление резюме                44744 non-null  object
 4   Авто                             44744 non-null  object
 5   Образование                      44744 non-null  object
 6   Пол                              44744 non-null  object
 7   Возраст                          44744 non-null  int64
 8   Опыт работы (месяц)              44574 non-null  float64
 9   Город                            44744 non-null  object
 10  Готовность к переезду            44744 non-null  bool
 11  Готовность к командировкам       44744 non-null  bool
 12  полная занятость                 44744 non-null  bool
 13  частичная занятость              44744 non-null  bool
 14  проектная работа                 44744 non-null  bool
 15  волонтерство                     44744 non-null  bool
 16  стажировка                       44744 non-null  bool
 17  полный день                      44744 non-null  bool
 18  сменный график                   44744 non-null  bool
 19  гибкий график                    44744 non-null  bool
 20  удалённая работа                 44744 non-null  bool
 21  вахтовый метод                   44744 non-null  bool
 22  ЗП (руб)                         44744 non-null  float64
dtypes: bool(12), float64(2), int64(1), object(8)
memory usage: 4.3+ MB

# Исследование зависимостей в данных

1. Постройте распределение признака **"Возраст"**. Опишите распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится возраст большинства соискателей? Есть ли аномалии для признака возраста, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [25]:
# ваш код здесь

fig = px.histogram(HeadHunter_data_feat_eng['Возраст'], 
                   x="Возраст", 
                   title='Распределение возраста соискателей',
                   nbins=100,
                   template='ggplot2',
                   marginal = 'box',
                   )

fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\hist_age.html")

#### ваши выводы по графику здесь


Описание признака "Возраст"

Мода распределения признака (наиболее частовстречающееся значение) - 30 лет.

Предельные значения: минимальное значение - 14 лет, максимальное значение 100 лет.

Возраст большинства соискателей находится примерно в интервале от 27 лет до 36 лет, что следует из границ "коробки" коробчатой диаграммы. То есть значений первого и третьего квартилей. Формально это интервал возраста не большинства, а средней половины соискателей.

Аномалиями распределения считаются точки данных, которые значительно отличаются от подавляющего большинства других наблюдей в наборе данных. В данном случае, опираясь на показания коробчатой диаграммы, можно причислить к аномалиям значения, находящиеся за пределами "усов", то есть значения меньше 14 лет и больше 49 лет.

2. Постройте распределение признака **"Опыт работы (месяц)"**. Опишите данное распределение, отвечая на следующие вопросы: чему равна мода распределения, каковы предельные значения признака, в каком примерном интервале находится опыт работы большинства соискателей? Есть ли аномалии для признака опыта работы, какие значения вы бы причислили к их числу?
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [26]:
# ваш код здесь


fig = px.histogram(HeadHunter_data_feat_eng['Опыт работы (месяц)'], 
                   x="Опыт работы (месяц)", 
                   title='Распределение опыта работы соискателей в месяцах',
                   nbins=1200,
                   template='ggplot2',
                   marginal = 'box',
                   )

fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\hist_expirience.html")

#### ваши выводы здесь

Описание признака "Опыт работы (месяц)"

Мода распределения признака (наиболее частовстречающееся значение) - 48 месяцев.

Предельные значения: минимальное значение - 1 месяц, максимальное значение 1188 месяцев.

Опыт большинства соискателей находится примерно в интервале от 48 месяцев до 154 месяцев, что следует из границ "коробки" коробчатой диаграммы. То есть значений первого и третьего квартилей. Формально это интервал опыта не большинства, а средней половины соискателей.

Аномалиями распределения считаются точки данных, которые значительно отличаются от подавляющего большинства других наблюдей в наборе данных. В данном случае, опираясь на показания коробчатой диаграммы, можно причислить к аномалиям значения, находящиеся за пределами "усов", то есть значения меньше 1 месяца и больше 313 месяцев.

3. Постройте распределение признака **"ЗП (руб)"**. Опишите данное распределение, отвечая на следующие вопросы: каковы предельные значения признака, в каком примерном интервале находится заработная плата большинства соискателей? Есть ли аномалии для признака возраста? Обратите внимание на гигантские размеры желаемой заработной платы.
*Совет: постройте гистограмму и коробчатую диаграмму рядом.*

In [27]:
# ваш код здесь

fig = px.histogram(HeadHunter_data_feat_eng['ЗП (руб)'], 
                   x="ЗП (руб)", 
                   title='Распределение ЗП соискателей в месяцах',
                   nbins=25000,
                   template='ggplot2',
                   marginal = 'box'
                   )

fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\hist_salary.html")

#### ваши выводы здесь

Описание признака "ЗП (руб)"

Мода распределения признака (наиболее частовстречающееся значение) - интервал от 49 500 рублей до 50 499 руб.

Предельные значения: минимальное значение - 1 руб., максимальное значение 24 304 880 руб.

Ожидаемая ЗП большинства соискателей находится примерно в интервале от 37 054 руб. до 95 000 руб., что следует из границ "коробки" коробчатой диаграммы. То есть значений первого и третьего квартилей. Формально это интервал опыта не большинства, а средней половины соискателей.

Аномалиями распределения считаются точки данных, которые значительно отличаются от подавляющего большинства других наблюдей в наборе данных. В данном случае, опираясь на показания коробчатой диаграммы, можно причислить к аномалиям значения, находящиеся за пределами "усов", то есть значения меньше 1 рубля и больше 180 900 руб.

4. Постройте диаграмму, которая показывает зависимость **медианной** желаемой заработной платы (**"ЗП (руб)"**) от уровня образования (**"Образование"**). Используйте для диаграммы данные о резюме, где желаемая заработная плата меньше 1 млн рублей.
*Сделайте выводы по представленной диаграмме: для каких уровней образования наблюдаются наибольшие и наименьшие уровни желаемой заработной платы? Как вы считаете, важен ли признак уровня образования при прогнозировании заработной платы?*

In [29]:
# ваш код здесь

salary_till_million = HeadHunter_data_feat_eng[HeadHunter_data_feat_eng['ЗП (руб)'] < 1000000]
bar_data = salary_till_million.groupby(
    by='Образование',
    as_index=False
).agg({'ЗП (руб)': 'median'})

fig = px.bar(
    data_frame=bar_data,
    x='Образование',
    y='ЗП (руб)',
    title='Медианная з/п по уровню образования'
)
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\Bar_salary_education.html")

#### ваши выводы здесь

Наименьший уровень желаемой ЗП наблюдается для среднего и среднего специального образования. Наибольший уровень желаемой ЗП наблюдается для высшего образования.
Признак высшего образования безусловно важен при прогнозировании ЗП, так как наблюдается явная связь между увеличением медианной ЗП и увеличением уровня образования.

5. Постройте диаграмму, которая показывает распределение желаемой заработной платы (**"ЗП (руб)"**) в зависимости от города (**"Город"**). Используйте для диаграммы данные о резюме, где желая заработная плата меньше 1 млн рублей.
*Сделайте выводы по полученной диаграмме: как соотносятся медианные уровни желаемой заработной платы и их размах в городах? Как вы считаете, важен ли признак города при прогнозировании заработной платы?*

In [30]:
# ваш код здесь

salary_till_million = HeadHunter_data_feat_eng[HeadHunter_data_feat_eng['ЗП (руб)'] < 1000000]


fig = px.box(
    data_frame=salary_till_million,
    x='Город',
    y='ЗП (руб)',
    color='Город',
    title='Распределение з/п по городам'
)
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\Box_salary_city.html")

#### ваши выводы здесь

Медианные уровни и размах ЗП в зависимости от города:

Москва - 85 000 руб. медиана, от 1 руб. до 900 000 руб. размах с аномальными значениями, от 1 руб. до 285 000 руб. размах буз учета аномальных значений.

Санкт-Петербург - 60 000 руб. медиана, от 1 руб. до 645 171 руб. размах с аномальными значениями, от 1 руб. до 145 000 руб. размах буз учета аномальных значений.

Город-миллионник - 40 000 руб. медиана, от 1 руб. до 511 682 руб. размах с аномальными значениями, от 1 руб. до 105 000 руб. размах буз учета аномальных значений.

Другие города - 40 000 руб. медиана, от 1 руб. до 923 983 руб. размах с аномальными значениями, от 1 руб. до 105 000 руб. размах буз учета аномальных значений.

Рассмотрении медианных уровней ЗП и размаха, включающего аномальные значения, дает искажение. Если для городов-миллионников, Санкт-Петербурга, Москвы наблюдается взаимосвязь - чем больше медианный уровень желаемой ЗП, тем больше размах, то для категории других городов, данная связь обратна, медиана на минимальном уровне, а размах максимальный.

Исключив из рассмотрения аномальные значения, можно заметить связь между размером города, медианной ЗП и размахом ЗП. Чем больше город, тем больше медиана ЗП и тем больше размах.

Признак города важен при прогнозировании ЗП, т.к. наблюдается связь между размером города и желаемым уровнем ЗП.

6. Постройте **многоуровневую столбчатую диаграмму**, которая показывает зависимость медианной заработной платы (**"ЗП (руб)"**) от признаков **"Готовность к переезду"** и **"Готовность к командировкам"**. Проанализируйте график, сравнив уровень заработной платы в категориях.

In [31]:
# ваш код здесь
bar_data = HeadHunter_data_feat_eng.groupby(
    ['Готовность к переезду','Готовность к командировкам'],
    as_index=False
).agg({'ЗП (руб)': 'median'})

fig = px.bar(
    data_frame=bar_data,
    y='Готовность к переезду',
    x='ЗП (руб)',
    barmode="group",
    color='Готовность к командировкам',
    orientation='h',
    title='Медианная з/п по готовности к командировкам/переезду'
)
fig.show()

fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\Bar_salary_relocation_worktrip.html")

#### ваши выводы здесь


Уровень медианной ЗП, если кандидат не готов ни к переезду, ни к командировкам - 40 000 руб.

Уровень медианной ЗП, если кандидат готов к переезду, но не готов к командировкам - 50 000 руб.

Уровень медианной ЗП, если кандидат не готов к переезду, но готов к командировкам - 60 000 руб.

Уровень медианной ЗП, если кандидат готов и к переезду, и к командировкам - 67 000 руб.

Наблюдается связь между мобильностью соискателя и желаемой медианной ЗП. Чем более мобилен кандидат, тем большей ЗП он ожидает.

7. Постройте сводную таблицу, иллюстрирующую зависимость **медианной** желаемой заработной платы от возраста (**"Возраст"**) и образования (**"Образование"**). На полученной сводной таблице постройте **тепловую карту**. Проанализируйте тепловую карту, сравнив показатели внутри групп.

In [32]:
# ваш код здесь

pivot = HeadHunter_data_feat_eng.pivot_table(
    values='ЗП (руб)',
    index='Образование',
    columns='Возраст',
    aggfunc='median',
    fill_value=0
)

fig = px.imshow(
    pivot,
    aspect='auto',
    color_continuous_scale='greens',
    title='Медианная з/п по образованию и возрасту'
)
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\imshow_salary_education_age.html")

#### ваши выводы здесь

Наиболее быстрый карьерный(зарплатный) рост наблюдается у группы с высшим образованием. Начиная с 18 лет, происходить плавный рост ЗП, и к 40 годам медианная ЗП составляет 90 000 руб. Также распределение ЗП по годам более равномерное и достигает больших значений по годам, чем в других группах.

Похожая ситуация у группы с неоконченным высшим образованием, рост ЗП начинается чуть позже, в целом медианные значения по годам ниже, чем у группы с высшим образованием, медианный уровень зп в 90 000 руб. достигается к 43 годам.

У группы со средним образованием на момент 18-25 лет медианная зп выше, чем у групп с высшим и неоконченным высшим образованием, однако после 25 лет значения остаются на практически тех же уровнях и существенно отстают от групп с высшим и неоконченным высшим образованием. Также медианная ЗП в 100 000 р. наблюдается у группы в  56 лет.

У группы со средним специальным образованием наблюдается равномерный, незначительный рост медианной ЗП в зависимости от возраста. На момент 40-45 лет медианная ЗП на уровне 45 000 руб, на момент 55-60 лет также на уровне 45 000 руб.

В целом наблюдается взаимосвязь медианной ожидаемой ЗП в зависимости от возраста и уровня образования. Чем выше уровень образования, тем больших значений достигает ЗП с увеличением возраста.

8. Постройте **диаграмму рассеяния**, показывающую зависимость опыта работы (**"Опыт работы (месяц)"**) от возраста (**"Возраст"**). Опыт работы переведите из месяцев в года, чтобы признаки были в едином масштабе. Постройте на графике дополнительно прямую, проходящую через точки (0, 0) и (100, 100). Данная прямая соответствует значениям, когда опыт работы равен возрасту человека. Точки, лежащие на этой прямой и выше нее - аномалии в наших данных (опыт работы больше либо равен возрасту соискателя)

In [33]:
# ваш код здесь
import plotly.graph_objects as go
scatter_data = HeadHunter_data_feat_eng[['Опыт работы (месяц)', 'Возраст']]
scatter_data['Опыт работы (месяц)'] = scatter_data['Опыт работы (месяц)'].fillna(0).apply(lambda x: round(x/12))
#строим график
fig = px.scatter(
    data_frame=scatter_data, #DataFrame
    x = 'Возраст', #ось абсцисс
    y = 'Опыт работы (месяц)', #ось ординат
    color='Возраст', #расцветка в зависимости от страны
    title="График зависимости опыта работы от возраста",
    log_x=True, 
    log_y=True,
    height= 1000

)

fig_line = px.line(pd.DataFrame([0,100], [0,100]))
#отображаем график
fig_combined = go.Figure(data=fig.data + fig_line.data)
fig_combined.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\scatter_age_expirience.html")

C:\Users\troyd\AppData\Local\Temp\ipykernel_11252\2686420498.py:4: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

#### ваши выводы 

На диаграмме наблюдается зависимость опыта работы от возраста. Небольшие значения опыта наблюдаются как у более молодых соискателей, так и у более возрастных. В данных случаях повышение опыта не зависит от повышения возраста. Если рассматривать максимальные значения опыта, то, чем более возрастной соискатель, тем большим опытом он обладает.

**Дополнительные баллы**

Для получения 2 дополнительных баллов по разведывательному анализу постройте еще два любых содержательных графика или диаграммы, которые помогут проиллюстрировать влияние признаков/взаимосвязь между признаками/распределения признаков. Приведите выводы по ним. Желательно, чтобы в анализе участвовали признаки, которые мы создавали ранее в разделе "Преобразование данных".

Построим график зависимости медианной ожидаемой заработной платы от возраста соискателя.

In [34]:
bar_data = HeadHunter_data_feat_eng.groupby(
    'Возраст',
    as_index=False
).agg({'ЗП (руб)': 'median'})

fig = px.line(bar_data, x="Возраст", y="ЗП (руб)", title="Зависимость зарплатных ожиданий от возраста соискателя")
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\line_salary_age.html")

#### ваши выводы

Заметно постепенное повышение зарплатных ожиданий от 17 до 40 лет. Далее прямая имеет незначительные колебания, демонстрируя некое плато, когда основные карьерные цели соискателей уже достигнуты и зарплатные ожидания изменяются незначительно, либо не изменяются.

Построим диаграмму зависимости медианной желаемой заработной платы от пола соискателя.

In [35]:
# ваш код здесь
bar_data = HeadHunter_data_feat_eng.groupby(
    'Пол',
    as_index=False
).agg({'ЗП (руб)': 'median'})

fig = px.bar(
    data_frame=bar_data,
    y='Пол',
    x='ЗП (руб)',
    barmode="group",
    color='Пол',
    #orientation='h',
    title='Медианная з/п по мужчинам и женщинам'
)
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\Bar_salary_sex.html")

#### Ваши выводы здесь

Для женщин медианная желаемая ЗП составляет 48 000 руб., для мужчин 60 тыс руб. Что показывает зависимость лжидаемой ЗП от пола соискателя.

# Очистка данных

1. Начнем с дубликатов в наших данных. Найдите **полные дубликаты** в таблице с резюме и удалите их.

In [36]:
# ваш код здесь


dupl_columns = list(HeadHunter_data_feat_eng.columns)
mask = HeadHunter_data_feat_eng.duplicated(subset=dupl_columns)
HeadHunter_data_feat_eng_duplicates = HeadHunter_data_feat_eng[mask]

HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop_duplicates(subset=dupl_columns)

2. Займемся пропусками. Выведите информацию **о числе пропусков** в столбцах.

In [37]:
# ваш код здесь

cols_null_percent = HeadHunter_data_feat_eng.isnull().sum()
cols_with_null = cols_null_percent[cols_null_percent>0].sort_values(ascending=False)
display(cols_with_null)

Опыт работы (месяц)                168
Последняя/нынешняя должность         2
Последнее/нынешнее место работы      1
dtype: int64

3. Итак, у нас есть пропуски в 3ех столбцах: **"Опыт работы (месяц)"**, **"Последнее/нынешнее место работы"**, **"Последняя/нынешняя должность"**. Поступим следующим образом: удалите строки, где есть пропуск в столбцах с местом работы и должностью. Пропуски в столбце с опытом работы заполните **медианным** значением.

In [38]:
# ваш код здесь
drop_data = HeadHunter_data_feat_eng.copy()
drop_data = drop_data.dropna(subset=['Последняя/нынешняя должность', 'Последнее/нынешнее место работы'], how='any', axis=0)
drop_data['Опыт работы (месяц)'] = drop_data['Опыт работы (месяц)'].fillna(drop_data['Опыт работы (месяц)'].median())
HeadHunter_data_feat_eng = drop_data
HeadHunter_data_feat_eng.shape

(44580, 23)

4. Мы добрались до ликвидации выбросов. Сначала очистим данные вручную. Удалите резюме, в которых указана заработная плата либо выше 1 млн. рублей, либо ниже 1 тыс. рублей.

In [39]:
# ваш код здесь
outliers = HeadHunter_data_feat_eng[(HeadHunter_data_feat_eng['ЗП (руб)'] > 1e6) | (HeadHunter_data_feat_eng['ЗП (руб)'] < 1e3)]
HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop(outliers.index)

5. В процессе разведывательного анализа мы обнаружили резюме, в которых **опыт работы в годах превышал возраст соискателя**. Найдите такие резюме и удалите их из данных

In [40]:
# ваш код здесь
outliers = HeadHunter_data_feat_eng[HeadHunter_data_feat_eng['Опыт работы (месяц)']/12 >= HeadHunter_data_feat_eng['Возраст']]
HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop(outliers.index)

6. В результате анализа мы обнаружили потенциальные выбросы в признаке **"Возраст"**. Это оказались резюме людей чересчур преклонного возраста для поиска работы. Попробуйте построить распределение признака в **логарифмическом масштабе**. Добавьте к графику линии, отображающие **среднее и границы интервала метода трех сигм**. Напомним, сделать это можно с помощью метода axvline. Например, для построение линии среднего будет иметь вид:

`histplot.axvline(log_age.mean(), color='k', lw=2)`

В какую сторону асимметрично логарифмическое распределение? Напишите об этом в комментарии к графику.
Найдите выбросы с помощью метода z-отклонения и удалите их из данных, используйте логарифмический масштаб. Давайте сделаем послабление на **1 сигму** (возьмите 4 сигмы) в **правую сторону**.

Выведите таблицу с полученными выбросами и оцените, с каким возрастом соискатели попадают под категорию выбросов?

In [41]:
log_age = np.log(HeadHunter_data_feat_eng['Возраст'])
# распределение с линиями среднего и сигм
fig = px.histogram(x=log_age, 
                   title='Распределение логарифма возраста',
                   labels={'x': 'ln(Возраст)', 'count': 'Количество'})
# добавляем линии
mean_log = log_age.mean() # среднее
std_log = log_age.std() # стандартное отклонение
fig.add_vline(x=mean_log, line_dash="dash", line_color="red", 
              annotation_text=f"Среднее: {mean_log:.2f}")
fig.add_vline(x=mean_log + 4*std_log, line_dash="dash", line_color="orange", 
              annotation_text=f"+4 sigma: {mean_log + 4*std_log:.2f}")
fig.add_vline(x=mean_log - 4*std_log, line_dash="dash", line_color="orange", 
              annotation_text=f"-3 sigma: {mean_log - 3*std_log:.2f}")
fig.show()
fig.write_html("C:\IDE\python_homework\Пайтон для анализа данных\Сессионное задание\Graphics\hist_log_age.html")

In [46]:

def outliers_z_score_mod(data, feature, log_scale=False, left = 3, right = 4):
    if isinstance(data, str):  # Проверка, если передан путь к файлу
        data = pd.read_csv(data)
    if log_scale:
        x = np.log(data[feature]+1)
    else:
        x = data[feature]
    mu = x.mean()
    sigma = x.std()
    lower_bound = mu - left * sigma
    upper_bound = mu + right * sigma
    outliers = data[(x < lower_bound) | (x > upper_bound)]
    cleaned = data[(x >= lower_bound) & (x <= upper_bound)]
    return outliers, cleaned

outliers, cleaned = outliers_z_score_mod(HeadHunter_data_feat_eng, feature='Возраст', log_scale=True, left = 3, right = 4)


outliers.index
display(HeadHunter_data_feat_eng['Возраст'].loc[[31137, 32950, 33654]])
HeadHunter_data_feat_eng = HeadHunter_data_feat_eng.drop(outliers.index)

31137     15
32950     15
33654    100
Name: Возраст, dtype: int64

### ваш коммментарий здесь

Логарифмическое распределение признака "Возраст" ассиметрично в правую сторону, так как среднее значение (красная пунктирная линия) находится правее моды.

Выведите таблицу с полученными выбросами

31137     15

32950     15

33654    100

Name: Возраст, dtype: int64

Под категорию выбросов попали соискатели с возрастом 15, 15, 100 лет.